# Copyright (C) 2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei//setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/huawei/venus/proprietary/vendor/etc/libnfc-brcm.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-brcm.conf \
    vendor/huawei/venus/proprietary/vendor/etc/libnfc-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp.conf \
    vendor/huawei/venus/proprietary/vendor/etc/cfg_venus_dl00_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_venus_dl00_hisi.ini \
    vendor/huawei/venus/proprietary/vendor/etc/cfg_venus_l21_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_venus_l21_hisi.ini \
    vendor/huawei/venus/proprietary/vendor/etc/cfg_venus_l22_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_venus_l22_hisi.ini \
    vendor/huawei/venus/proprietary/vendor/etc/cfg_venus_l23_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_venus_l23_hisi.ini \
    vendor/huawei/venus/proprietary/vendor/etc/cfg_venus_l31_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_venus_l31_hisi.ini \
    vendor/huawei/venus/proprietary/vendor/etc/cfg_venus_l53_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_venus_l53_hisi.ini \
    vendor/huawei/venus/proprietary/vendor/etc/cfg_venus_tl00_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_venus_tl00_hisi.ini \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.p.HI843_OFILM.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.p.HI843_OFILM.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.p.IMX214_FOXCONN.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.p.IMX214_FOXCONN.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.p.IMX214_OFILM.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.p.IMX214_OFILM.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.p.IMX214_SUNNY.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.p.IMX214_SUNNY.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.p.IMX219_LITEON.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.p.IMX219_LITEON.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.p.IMX219_SUNNY.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.p.IMX219_SUNNY.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.p.OV8856_SUNNY.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.p.OV8856_SUNNY.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.p.T4KA3_LITEON.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.p.T4KA3_LITEON.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.s.HI843_OFILM.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.s.HI843_OFILM.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.s.IMX214_FOXCONN.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.s.IMX214_FOXCONN.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.s.IMX214_OFILM.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.s.IMX214_OFILM.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.s.IMX214_SUNNY.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.s.IMX214_SUNNY.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.s.IMX219_LITEON.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.s.IMX219_LITEON.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.s.IMX219_SUNNY.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.s.IMX219_SUNNY.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.s.OV8856_SUNNY.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.s.OV8856_SUNNY.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.s.T4KA3_LITEON.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.s.T4KA3_LITEON.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.m.VENUS.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.m.VENUS.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.p.HI843_OFILM.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.p.HI843_OFILM.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.p.IMX214_FOXCONN.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.p.IMX214_FOXCONN.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.p.IMX214_OFILM.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.p.IMX214_OFILM.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.p.IMX214_SUNNY.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.p.IMX214_SUNNY.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.p.IMX219_LITEON.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.p.IMX219_LITEON.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.p.IMX219_SUNNY.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.p.IMX219_SUNNY.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.p.OV8856_SUNNY.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.p.OV8856_SUNNY.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.p.T4KA3_LITEON.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.p.T4KA3_LITEON.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.s.HI843_OFILM.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.s.HI843_OFILM.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.s.IMX214_FOXCONN.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.s.IMX214_FOXCONN.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.s.IMX214_OFILM.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.s.IMX214_OFILM.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.s.IMX214_SUNNY.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.s.IMX214_SUNNY.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.s.IMX219_LITEON.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.s.IMX219_LITEON.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.s.IMX219_SUNNY.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.s.IMX219_SUNNY.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.s.OV8856_SUNNY.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.s.OV8856_SUNNY.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.s.T4KA3_LITEON.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.s.T4KA3_LITEON.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.m.VENUS.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.m.VENUS.so
