# Copyright (C) 2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei//setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/huawei/venus/proprietary/vendor/etc/audio/algorithm/algorithm_VENUS2_normal.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/algorithm/algorithm_VENUS2_normal.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/algorithm/algorithm_VENUS3_normal.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/algorithm/algorithm_VENUS3_normal.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/algorithm/algorithm_VENUS_normal.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/algorithm/algorithm_VENUS_normal.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/dts/dts_VENUS2_normal.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/dts/dts_VENUS2_normal.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/dts/dts_VENUS3_normal.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/dts/dts_VENUS3_normal.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/dts/dts_VENUS_normal.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/dts/dts_VENUS_normal.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/hi6402/mixer_paths_VENUS.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/hi6402/mixer_paths_VENUS.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/hi6402/mixer_paths_VENUS2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/hi6402/mixer_paths_VENUS2.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/hi6402/mixer_volumes_VENUS2_ce.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/hi6402/mixer_volumes_VENUS2_ce.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/hi6402/mixer_volumes_VENUS2_cmcciot.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/hi6402/mixer_volumes_VENUS2_cmcciot.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/hi6402/mixer_volumes_VENUS2_normal.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/hi6402/mixer_volumes_VENUS2_normal.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/hi6402/mixer_volumes_VENUS2_unicomiot.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/hi6402/mixer_volumes_VENUS2_unicomiot.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/hi6402/mixer_volumes_VENUS_ce.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/hi6402/mixer_volumes_VENUS_ce.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/hi6402/mixer_volumes_VENUS_cmcciot.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/hi6402/mixer_volumes_VENUS_cmcciot.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/hi6402/mixer_volumes_VENUS_normal.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/hi6402/mixer_volumes_VENUS_normal.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/hi6402/mixer_volumes_VENUS_unicomiot.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/hi6402/mixer_volumes_VENUS_unicomiot.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/hi6402/pop_seq_VENUS.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/hi6402/pop_seq_VENUS.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/hi6402/pop_seq_VENUS2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/hi6402/pop_seq_VENUS2.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/hissc/mixer_paths_VENUS3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/hissc/mixer_paths_VENUS3.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/hissc/mixer_volumes_VENUS3_ce.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/hissc/mixer_volumes_VENUS3_ce.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/hissc/mixer_volumes_VENUS3_cmcciot.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/hissc/mixer_volumes_VENUS3_cmcciot.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/hissc/mixer_volumes_VENUS3_normal.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/hissc/mixer_volumes_VENUS3_normal.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/hissc/mixer_volumes_VENUS3_unicomiot.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/hissc/mixer_volumes_VENUS3_unicomiot.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/hissc/pop_seq_VENUS3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/hissc/pop_seq_VENUS3.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/maxim/maxim_VENUS_normal.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/maxim/maxim_VENUS_normal.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/mbdrc/mbdrc_VENUS2_normal.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/mbdrc/mbdrc_VENUS2_normal.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/mbdrc/mbdrc_VENUS3_normal.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/mbdrc/mbdrc_VENUS3_normal.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/mbdrc/mbdrc_VENUS_normal.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/mbdrc/mbdrc_VENUS_normal.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/modem/modem_VENUS2_cmcciot.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/modem/modem_VENUS2_cmcciot.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/modem/modem_VENUS2_normal.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/modem/modem_VENUS2_normal.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/modem/modem_VENUS2_unicomiot.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/modem/modem_VENUS2_unicomiot.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/modem/modem_VENUS3_cmcciot.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/modem/modem_VENUS3_cmcciot.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/modem/modem_VENUS3_normal.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/modem/modem_VENUS3_normal.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/modem/modem_VENUS3_unicomiot.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/modem/modem_VENUS3_unicomiot.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/modem/modem_VENUS_cmcciot.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/modem/modem_VENUS_cmcciot.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/modem/modem_VENUS_normal.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/modem/modem_VENUS_normal.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/modem/modem_VENUS_unicomiot.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/modem/modem_VENUS_unicomiot.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/nxp/Tfa9895_VENUS2.cnt:$(TARGET_COPY_OUT_VENDOR)/etc/audio/nxp/Tfa9895_VENUS2.cnt \
    vendor/huawei/venus/proprietary/vendor/etc/audio/nxp/Tfa9895_VENUS2_AAC.cnt:$(TARGET_COPY_OUT_VENDOR)/etc/audio/nxp/Tfa9895_VENUS2_AAC.cnt \
    vendor/huawei/venus/proprietary/vendor/etc/audio/nxp/Tfa9895_VENUS2_GD.cnt:$(TARGET_COPY_OUT_VENDOR)/etc/audio/nxp/Tfa9895_VENUS2_GD.cnt \
    vendor/huawei/venus/proprietary/vendor/etc/audio/nxp/Tfa9895_VENUS2_GK.cnt:$(TARGET_COPY_OUT_VENDOR)/etc/audio/nxp/Tfa9895_VENUS2_GK.cnt \
    vendor/huawei/venus/proprietary/vendor/etc/audio/nxp/Tfa9895_VENUS2_LC.cnt:$(TARGET_COPY_OUT_VENDOR)/etc/audio/nxp/Tfa9895_VENUS2_LC.cnt \
    vendor/huawei/venus/proprietary/vendor/etc/audio/nxp/Tfa9895_VENUS3.cnt:$(TARGET_COPY_OUT_VENDOR)/etc/audio/nxp/Tfa9895_VENUS3.cnt \
    vendor/huawei/venus/proprietary/vendor/etc/audio/nxp/Tfa9895_VENUS3_AAC.cnt:$(TARGET_COPY_OUT_VENDOR)/etc/audio/nxp/Tfa9895_VENUS3_AAC.cnt \
    vendor/huawei/venus/proprietary/vendor/etc/audio/nxp/Tfa9895_VENUS3_GD.cnt:$(TARGET_COPY_OUT_VENDOR)/etc/audio/nxp/Tfa9895_VENUS3_GD.cnt \
    vendor/huawei/venus/proprietary/vendor/etc/audio/nxp/Tfa9895_VENUS3_GK.cnt:$(TARGET_COPY_OUT_VENDOR)/etc/audio/nxp/Tfa9895_VENUS3_GK.cnt \
    vendor/huawei/venus/proprietary/vendor/etc/audio/nxp/Tfa9895_VENUS3_LC.cnt:$(TARGET_COPY_OUT_VENDOR)/etc/audio/nxp/Tfa9895_VENUS3_LC.cnt \
    vendor/huawei/venus/proprietary/vendor/etc/audio/sws/sws_VENUS2_normal.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sws/sws_VENUS2_normal.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/sws/sws_VENUS3_normal.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sws/sws_VENUS3_normal.xml \
    vendor/huawei/venus/proprietary/vendor/etc/audio/sws/sws_VENUS_normal.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sws/sws_VENUS_normal.xml \
    vendor/huawei/venus/proprietary/vendor/etc/firmware/nfc/libpn548ad_fw.so:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nfc/libpn548ad_fw.so \
    vendor/huawei/venus/proprietary/vendor/etc/firmware/nfc/libpn548ad_fw_10.01.1C_64bits.so:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nfc/libpn548ad_fw_10.01.1C_64bits.so \
    vendor/huawei/venus/proprietary/vendor/etc/firmware/ts/venus_synaptics_VENS11080_jdi.img:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/ts/venus_synaptics_VENS11080_jdi.img \
    vendor/huawei/venus/proprietary/vendor/etc/firmware/ts/venus_synaptics_VENS11120_cmi.img:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/ts/venus_synaptics_VENS11120_cmi.img \
    vendor/huawei/venus/proprietary/vendor/etc/firmware/ts/venus_synaptics_VENS11130_boe.img:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/ts/venus_synaptics_VENS11130_boe.img \
    vendor/huawei/venus/proprietary/vendor/etc/firmware/ts/venus_synaptics_VENS11140_ebbg.img:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/ts/venus_synaptics_VENS11140_ebbg.img \
    vendor/huawei/venus/proprietary/vendor/etc/firmware/ts/venus_synaptics_VENS11190_boe-ramless.img:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/ts/venus_synaptics_VENS11190_boe-ramless.img \
    vendor/huawei/venus/proprietary/vendor/etc/firmware/ts/venus_synaptics_VENS11200_ebbg-ramless.img:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/ts/venus_synaptics_VENS11200_ebbg-ramless.img \
    vendor/huawei/venus/proprietary/vendor/etc/firmware/ts/venus_synaptics_VENS18100_lg.img:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/ts/venus_synaptics_VENS18100_lg.img \
    vendor/huawei/venus/proprietary/vendor/etc/libnfc-brcm.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-brcm.conf \
    vendor/huawei/venus/proprietary/vendor/etc/libnfc-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp.conf \
    vendor/huawei/venus/proprietary/vendor/etc/cfg_venus_dl00_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_venus_dl00_hisi.ini \
    vendor/huawei/venus/proprietary/vendor/etc/cfg_venus_l21_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_venus_l21_hisi.ini \
    vendor/huawei/venus/proprietary/vendor/etc/cfg_venus_l22_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_venus_l22_hisi.ini \
    vendor/huawei/venus/proprietary/vendor/etc/cfg_venus_l23_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_venus_l23_hisi.ini \
    vendor/huawei/venus/proprietary/vendor/etc/cfg_venus_l31_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_venus_l31_hisi.ini \
    vendor/huawei/venus/proprietary/vendor/etc/cfg_venus_l53_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_venus_l53_hisi.ini \
    vendor/huawei/venus/proprietary/vendor/etc/cfg_venus_tl00_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_venus_tl00_hisi.ini \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.p.HI843_OFILM.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.p.HI843_OFILM.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.p.IMX214_FOXCONN.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.p.IMX214_FOXCONN.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.p.IMX214_OFILM.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.p.IMX214_OFILM.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.p.IMX214_SUNNY.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.p.IMX214_SUNNY.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.p.IMX219_LITEON.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.p.IMX219_LITEON.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.p.IMX219_SUNNY.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.p.IMX219_SUNNY.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.p.OV8856_SUNNY.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.p.OV8856_SUNNY.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.p.T4KA3_LITEON.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.p.T4KA3_LITEON.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.s.HI843_OFILM.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.s.HI843_OFILM.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.s.IMX214_FOXCONN.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.s.IMX214_FOXCONN.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.s.IMX214_OFILM.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.s.IMX214_OFILM.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.s.IMX214_SUNNY.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.s.IMX214_SUNNY.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.s.IMX219_LITEON.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.s.IMX219_LITEON.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.s.IMX219_SUNNY.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.s.IMX219_SUNNY.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.s.OV8856_SUNNY.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.s.OV8856_SUNNY.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.VENUS.s.T4KA3_LITEON.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.VENUS.s.T4KA3_LITEON.so \
    vendor/huawei/venus/proprietary/vendor/lib/hwcam/hwcam.hi6250.m.VENUS.so:$(TARGET_COPY_OUT_VENDOR)/lib/hwcam/hwcam.hi6250.m.VENUS.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.p.HI843_OFILM.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.p.HI843_OFILM.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.p.IMX214_FOXCONN.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.p.IMX214_FOXCONN.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.p.IMX214_OFILM.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.p.IMX214_OFILM.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.p.IMX214_SUNNY.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.p.IMX214_SUNNY.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.p.IMX219_LITEON.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.p.IMX219_LITEON.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.p.IMX219_SUNNY.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.p.IMX219_SUNNY.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.p.OV8856_SUNNY.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.p.OV8856_SUNNY.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.p.T4KA3_LITEON.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.p.T4KA3_LITEON.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.s.HI843_OFILM.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.s.HI843_OFILM.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.s.IMX214_FOXCONN.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.s.IMX214_FOXCONN.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.s.IMX214_OFILM.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.s.IMX214_OFILM.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.s.IMX214_SUNNY.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.s.IMX214_SUNNY.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.s.IMX219_LITEON.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.s.IMX219_LITEON.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.s.IMX219_SUNNY.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.s.IMX219_SUNNY.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.s.OV8856_SUNNY.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.s.OV8856_SUNNY.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.VENUS.s.T4KA3_LITEON.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.VENUS.s.T4KA3_LITEON.so \
    vendor/huawei/venus/proprietary/vendor/lib64/hwcam/hwcam.hi6250.m.VENUS.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hwcam/hwcam.hi6250.m.VENUS.so
